# Site settings
title: Minseung Choi
email: minseung@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a 5th-year student in the Neurosciences PhD Program at Stanford University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://minseung.com" # the base hostname & protocol for your site
twitter_username: Bach__choi
github_username:  minseungchoi
orcid_id: 0000-0001-5398-219X
google_scholar_id: 6GvJhS0AAAAJ

# Header settings
header_texture: "/images/pattern.png"

# Icons
icon_32: "/images/icons/icon-m-block-32.png"
icon_192: "/images/icons/icon-m-block-192.png"

# Default image
default_image: "/images/minseung_at_ross_cove.jpg"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "PhD Candidate"
excerpt_separator: "<!--more-->"

# Disqus
disqus_shortname: 'minseung'

# SEO stuff
#google_author: "https://plus.google.com/u/0/110288225974212014913"
#google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
#bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins:
  - jekyll-sitemap

include: ['_css']
exclude: ['develop', '_stashed']

dateformat: "%a %-m/%-d/%Y"
onlydateformat: "%-m/%-d/%Y"
timeformat: "%-I:%M %p"
